### PR TITLE
Pass current git commit SHA to docker image via docker build args

### PR DESCRIPTION
**Pull request by NazmiAltun**
Git commit hash will be used as sentry release identifier

### CODE REVIEW

**Review by andreyleskov — CHANGES_REQUESTED** [review]
If we need a release identifier, it is already there - you can use app_version. 

Add git commit sha to the image is great, the only question is how. 
When we build a versioned image and pass build args, we risk missing the build cache. If we like to add a unique identifier to every commit during the build, we sacrifice most of the cache intentionally. App_version has the same issue - if we pass it for each build, we sacrifice the cache for each build (longer CI)

What do you think about adding git commit sha as a label to the docker image and putting it into the "labels" of the image?
It would allow to move this step to after build, keeping the cache.  

  @NazmiAltun

**Comment by NazmiAltun** [comment]
> If we need a release identifier, it is already there - you can use app_version.
> 
> Add git commit sha to the image is great, the only question is how. When we build a versioned image and pass build args, we risk missing the build cache. If we like to add a unique identifier to every commit during the build, we sacrifice most of the cache intentionally. App_version has the same issue - if we pass it for each build, we sacrifice the cache for each build (longer CI)
> 
> What do you think about adding git commit sha as a label to the docker image and putting it into the "labels" of the image? It would allow to move this step to after build, keeping the cache.

Yeah, I need a release identifier. I guess, I can use app_version , I wanted to use commit hash because it was recommended by [sentry](https://docs.sentry.io/platforms/javascript/configuration/releases/#bind-the-version).  I will go with app_version first.

I'll try app_version first, then if that doesn't work, I will continue working on this one.

@andreyleskov

**Comment by NazmiAltun** [comment]
@andreyleskov 

I came across this one : https://docs.docker.com/engine/reference/builder/#impact-on-build-caching

> However, ARG variables do impact the build cache in similar ways. If a Dockerfile defines an ARG variable whose value is different from a previous build, then a “cache miss” occurs upon its first usage, not its definition.


So what if we add it at the of the Dockerfile ? The cache miss will be something neglectable,  no? Something like ;



image


Would it make sense?

**Review by andreyleskov — APPROVED** [review]

**Comment by andreyleskov** [comment]
> @andreyleskov
> 
> I came across this one : https://docs.docker.com/engine/reference/builder/#impact-on-build-caching
> 
> > However, ARG variables do impact the build cache in similar ways. If a Dockerfile defines an ARG variable whose value is different from a previous build, then a “cache miss” occurs upon its first usage, not its definition.
> 
> So what if we add it at the of the Dockerfile ? The "cache miss" will be something neglectable, no? Something like ;
> 
> image
> 
> Would it make sense?

Yep, this makes full sense.

**Comment by andreyleskov** [comment]
> > If we need a release identifier, it is already there - you can use app_version.
> > Add git commit sha to the image is great, the only question is how. When we build a versioned image and pass build args, we risk missing the build cache. If we like to add a unique identifier to every commit during the build, we sacrifice most of the cache intentionally. App_version has the same issue - if we pass it for each build, we sacrifice the cache for each build (longer CI)
> > What do you think about adding git commit sha as a label to the docker image and putting it into the "labels" of the image? It would allow to move this step to after build, keeping the cache.
> 
> Yeah, I need a release identifier. I guess, I can use app_version , I wanted to use commit hash because it was recommended by [sentry](https://docs.sentry.io/platforms/javascript/configuration/releases/#bind-the-version). I will go with app_version first.
> 
> I'll try app_version first, then if that doesn't work, I will continue working on this one.
> 
> @andreyleskov

If we are aware of build cache miss risk, we are fine to add any additional args.

**Pull request merged**
